name: 'NamingConvention action using C#'
branding:
  icon: arrow-right-circle
  color: red
inputs:
  path:
    description: 'Folder path'
    required: true
    default: 'unknown'
  environment:
    description: 'Environment to deploy'
    required: true
    default: 'unknown'
  product:
    description: 'Product'
    required: true
    default: 'unknown'
outputs:
  FolderName:
    description:
      'the folder name used to determine the group of functions'
  RgName:
    description:
      'the resource group name'
  ApimName:
    description:
      'The azure api management name'
  ApiPath:
    description:
      'the azure api management api path'
  FunctionName:
    description:
      'the azure function name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - path
    - ${{ inputs.path }}
    - env
    - ${{ inputs.environment }}
    - product
    - ${{ inputs.product }}
  entrypoint: "/app/entrypoint.sh"
