name: Testing True eval
run-name: Testing True Evaluation

on: 
  push:
    branches:
      - main
      - develop
  
  workflow_dispatch:
    inputs:
      test_bool:
        required: true
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read


jobs:
  first:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: echo test
        id: test
        run: |
          if [ ${{ env.TEST_BOOL }} ]; then
            echo "Hello! TEST_BOOL == true worked" 
          else 
            echo "Goodbye!"
          fi
