name: Testing True eval
run-name: Testing True Evaluation

on: 
  push:
    branches:
      - main
      - develop
  
  workflow_dispatch:

env:
  TEST_BOOL: false

permissions:
  id-token: write
  contents: read


jobs:
  first:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: echo test
        id: test
        run: |
          if [ ${{ env.TEST_BOOL }} ]
            echo "Hello! TEST_BOOL == true worked" 
          fi
