name: Testing True eval
run-name: Testing True Evaluation

on: 
  push:
    branches:
      - main
      - develop
  
  workflow_dispatch:
    inputs:
      test_bool:
        required: true
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read


jobs:
  first:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: echo test
        id: test
        run: |
          echo ${{ inputs.test_bool }}
          if [ ${{ inputs.test_bool }} ]; then
            echo "Hello!"
          else
            echo "Goodbye!"
          fi
