name: Testing True eval
run-name: Testing True Evaluation

on: 
  push:
    branches:
      - main
      - develop
  
  workflow_dispatch:
    inputs:
      test_bool:
        required: True
        type: boolean
        default: True

permissions:
  id-token: write
  contents: read


jobs:
  first:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: echo test
        uses: azure/powershell@v1
        id: test
        with:
          inlineScript: |
            echo "Starting script with input: '${{ inputs.test_bool }}'"
            if ('${{ inputs.test_bool }}' -eq 'true') {
                echo "Hello!"
              }
            else {
                echo "Goodbye!"
              }
          azPSVersion: "latest"        
